### ISSUE TITLE
Use IO adapter?

### ISSUE THREAD

**Issue by Luctins** [embassy-rs/ppproto#4]
Could we accept a `embedded-io`/`embedded-io-async` `Read` + `Write` (or `Read` + `BufRead`) implementor instead of using a `poll` method?

This way the crate can still abstract away how the bytes are sent while probably being more efficient.

**Comment by Dirbaio** [comment]
it's written this way so it works for any IO model. using `embedded-io` would tie it to blocking IO which is not great if you want to do something else while waiting for data, and `embedded-io-async` would tie it to async. With the current API the crate works also for "manual polling, non-blocking" use cases.

[embassy-net-ppp](https://github.com/embassy-rs/embassy/blob/main/embassy-net-ppp) has an adapter that works with `embedded-io-async`, maybe that's closer to what you're looking for.

**Comment by Luctins** [comment]
That makes sense; I wanted mostly to understand the reasoning behind not using embedded traits and having `poll`. Do you think there is some performance to be gained by not using poll (and having `#[cfg()]` guards maybe)?

I also use `embassy-net-ppp` in one of my projects, and have taken a look at the source, so that is where my question mostly comes from.

**Comment by Dirbaio** [comment]
> Do you think there is some performance to be gained by not using poll (and having #[cfg()] guards maybe)?

I don't think so (as long as the adapter takes care to only poll when something actually changed, of course). In the end the stack would do about the same work than if ppproto used embedded-io directly.

**Comment by Luctins** [comment]
That makes sense, thanks for the input.
